'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace ScatterRadarLine


    Partial Public Class _Default

        ''' <summary>
        ''' WebChartControl1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected WebChartControl1 As Global.DevExpress.XtraCharts.Web.WebChartControl
    End Class
End Namespace
