'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace ScatterRadarLine.Account


    Partial Public Class Manage

        ''' <summary>
        ''' successMessage control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>

        Protected successMessage_Renamed As Global.System.Web.UI.WebControls.PlaceHolder

        ''' <summary>
        ''' setPassword control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected setPassword As Global.System.Web.UI.WebControls.PlaceHolder

        ''' <summary>
        ''' password control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected password As Global.System.Web.UI.WebControls.TextBox



        ''' <summary>
        ''' confirmPassword control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected confirmPassword As Global.System.Web.UI.WebControls.TextBox

        ''' <summary>
        ''' changePassword control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected changePassword As Global.System.Web.UI.WebControls.PlaceHolder


    End Class
End Namespace
