'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace ScatterRadarLine.Account


    Partial Public Class RegisterExternalLogin



        ''' <summary>
        ''' userNameForm control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected userNameForm As Global.System.Web.UI.WebControls.PlaceHolder

        ''' <summary>
        ''' userName control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected userName As Global.System.Web.UI.WebControls.TextBox


    End Class
End Namespace
